services:
  broker:
    build: ./broker
    ports:
      - "10000:10000/udp"
      - "12000:12000/tcp"

  trajectory:
    build: ./trajectory
    ports:
      - "13000:13000/tcp"
    depends_on:
      - broker
